import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {

    @Test
    public void testMain() {
        // Assuming App has a method called getGreeting that returns a greeting message
        App app = new App();
        String expected = "Hello, World!";
        String actual = app.getGreeting();
        assertEquals(expected, actual);
    }

    @Test
    public void testCalculatePi() {
        // Test that calculatePi approximates Math.PI within a reasonable error margin
        double piApprox = App.calculatePi(1000000);
        assertTrue(Math.abs(piApprox - Math.PI) < 0.0001, "Pi approximation is not accurate enough");
    }
}

// Generated by Copilot