// Generated by Copilot
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import ExampleComponent from './ExampleComponent';

// Example: Mock a module dependency
// jest.mock('../api/someApi', () => ({
//     fetchData: jest.fn(() => Promise.resolve({ data: 'mocked data' }))
// }));

// Example: Mock a child component
// jest.mock('./ChildComponent', () => () => <div>Mocked Child</div>);

test('renders ExampleComponent with Hello World', () => {
    render(<ExampleComponent />);
    // Check for the actual text rendered by ExampleComponent
    const element = screen.getByText(/hello world/i);
    expect(element).toBeInTheDocument();
});