import React from 'react';

// Generated by Copilot

/**
 * ExampleComponent displays a simple greeting message.
 * Generated by Copilot
 */
const ExampleComponent: React.FC = () => {
    return (
        <div>
            <h1>Hello from ExampleComponent!</h1>
        </div>
    );
};

export default ExampleComponent;