// Generated by Copilot
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom";
import Notifications from "./Notifications";
import { Notification } from "./types";

const notifications: Notification[] = [
  { id: 1, message: "Info message", type: "info" },
  { id: 2, message: "Warning message", type: "warning" },
  { id: 3, message: "Error message", type: "error" },
];

test("renders Notifications and toggles visibility", () => {
  const handleToggle = jest.fn();
  render(
    <Notifications notifications={notifications} show={true} onToggle={handleToggle} />
  );
  expect(screen.getByText(/Hide Notifications/i)).toBeInTheDocument();
  expect(screen.getByText(/Info message/i)).toBeInTheDocument();
  expect(screen.getByText(/Warning message/i)).toBeInTheDocument();
  expect(screen.getByText(/Error message/i)).toBeInTheDocument();

  fireEvent.click(screen.getByRole("button"));
  expect(handleToggle).toHaveBeenCalled();
});

test("hides notifications when show is false", () => {
  render(
    <Notifications notifications={notifications} show={false} onToggle={() => {}} />
  );
  expect(screen.getByText(/Show Notifications/i)).toBeInTheDocument();
  expect(screen.queryByText(/Info message/i)).not.toBeInTheDocument();
});
