// Generated by Copilot

import React from "react";
import { Notification } from "./types";

/**
 * Notifications component displays a list of notifications with ARIA support.
 * Generated by Copilot
 */
const Notifications: React.FC<NotificationsProps> = ({ notifications, show, onToggle }) => (
  <section aria-live="polite">
    <button onClick={onToggle} aria-pressed={show}>
      {show ? "Hide" : "Show"} Notifications
    </button>
    {show && (
      <ul>
        {notifications.slice(-10).map((n) => (
          <li
            key={n.id}
            style={{
              color:
                n.type === "warning"
                  ? "orange"
                  : n.type === "error"
                  ? "red"
                  : "green",
            }}
            aria-label={n.type}
          >
            {n.message}
          </li>
        ))}
      </ul>
    )}
  </section>
);

export default Notifications;
