// Generated by Copilot

import React from "react";
import { Todo } from "./types";

/**
 * TodoList component displays a list of todos with bulk actions and accessibility.
 * Generated by Copilot
 */
const TodoList: React.FC<TodoListProps> = ({
  todos,
  todoText,
  onTodoTextChange,
  onAddTodo,
  onToggleTodo,
  onDeleteTodo,
  searchTodo,
  setSearchTodo,
  bulkSelect,
  onBulkSelect,
  showBulkActions,
  setShowBulkActions,
  onBulkDelete,
}) => (
  <section>
    <h3>Todos</h3>
    <input
      value={searchTodo}
      onChange={(e) => setSearchTodo(e.target.value)}
      placeholder="Search todos"
      aria-label="Search todos"
    />
    <input
      value={todoText}
      onChange={(e) => onTodoTextChange(e.target.value)}
      placeholder="Add todo"
      aria-label="Add todo"
    />
    <button onClick={onAddTodo}>Add</button>
    <button onClick={() => setShowBulkActions(!showBulkActions)}>
      {showBulkActions ? "Hide" : "Show"} Bulk Actions
    </button>
    {showBulkActions && (
      <button onClick={onBulkDelete} disabled={bulkSelect.length === 0}>
        Delete Selected
      </button>
    )}
    <ul>
      {todos.map((todo) => (
        <li key={todo.id}>
          <input
            type="checkbox"
            checked={bulkSelect.includes(todo.id)}
            onChange={() => onBulkSelect(todo.id)}
            aria-label={`Select todo ${todo.text}`}
          />
          <span
            style={{
              textDecoration: todo.completed ? "line-through" : "none",
              cursor: "pointer",
            }}
            onClick={() => onToggleTodo(todo.id)}
            tabIndex={0}
            role="button"
            aria-pressed={todo.completed}
          >
            {todo.text}
          </span>
          <button onClick={() => onDeleteTodo(todo.id)}>Delete</button>
        </li>
      ))}
    </ul>
  </section>
);

export default TodoList;
