// Generated by Copilot
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom";
import TodoList from "./TodoList";
import { Todo } from "./types";

const todos: Todo[] = [
  { id: 1, text: "Learn React", completed: false },
  { id: 2, text: "Build a project", completed: true },
];

test("renders TodoList and handles actions", () => {
  const onTodoTextChange = jest.fn();
  const onAddTodo = jest.fn();
  const onToggleTodo = jest.fn();
  const onDeleteTodo = jest.fn();
  const onBulkSelect = jest.fn();
  const setSearchTodo = jest.fn();
  const setShowBulkActions = jest.fn();
  const onBulkDelete = jest.fn();

  render(
    <TodoList
      todos={todos}
      todoText=""
      onTodoTextChange={onTodoTextChange}
      onAddTodo={onAddTodo}
      onToggleTodo={onToggleTodo}
      onDeleteTodo={onDeleteTodo}
      searchTodo=""
      setSearchTodo={setSearchTodo}
      bulkSelect={[]}
      onBulkSelect={onBulkSelect}
      showBulkActions={false}
      setShowBulkActions={setShowBulkActions}
      onBulkDelete={onBulkDelete}
    />
  );

  expect(screen.getByText(/Todos/i)).toBeInTheDocument();
  expect(screen.getByPlaceholderText(/Search todos/i)).toBeInTheDocument();
  expect(screen.getByPlaceholderText(/Add todo/i)).toBeInTheDocument();
  expect(screen.getByText(/Add/i)).toBeInTheDocument();
  expect(screen.getByText(/Show Bulk Actions/i)).toBeInTheDocument();
  expect(screen.getByText(/Learn React/i)).toBeInTheDocument();
  expect(screen.getByText(/Build a project/i)).toBeInTheDocument();

  fireEvent.click(screen.getByText(/Add/i));
  expect(onAddTodo).toHaveBeenCalled();

  fireEvent.click(screen.getAllByText(/Delete/i)[0]);
  expect(onDeleteTodo).toHaveBeenCalled();
});
