// Generated by Copilot
import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import Tokenizer from './Tokenizer';

// Mock the getTokens service
jest.mock('../services/Service', () => ({
    getTokens: jest.fn(async (text: string, model: string) => ({
        tokens: text ? text.split('') : []
    }))
}));

describe('Tokenizer', () => {
    test('renders headings and UI elements', async () => {
        render(<Tokenizer />);
        expect(screen.getByText(/Tokenizer/i)).toBeInTheDocument();
        expect(screen.getByText(/Learn about language model tokenization/i)).toBeInTheDocument();
        expect(screen.getByRole('textbox')).toBeInTheDocument();
        expect(screen.getByText(/Clear/i)).toBeInTheDocument();
        expect(screen.getByText(/Show example/i)).toBeInTheDocument();
        expect(screen.getByText(/Tokens/i)).toBeInTheDocument();
        expect(screen.getByText(/Characters/i)).toBeInTheDocument();
        // Wait for tokens to be displayed
        await waitFor(() => expect(screen.getByText('6')).toBeInTheDocument());
    });

    test('updates token and character count on input', async () => {
        render(<Tokenizer />);
        const textarea = screen.getByRole('textbox');
        fireEvent.change(textarea, { target: { value: 'abc' } });
        await waitFor(() => expect(screen.getByText('3')).toBeInTheDocument());
    });

    test('clears input and tokens', async () => {
        render(<Tokenizer />);
        const textarea = screen.getByRole('textbox');
        fireEvent.change(textarea, { target: { value: 'abc' } });
        await waitFor(() => expect(screen.getByText('3')).toBeInTheDocument());
        fireEvent.click(screen.getByText(/Clear/i));
        await waitFor(() => expect(screen.getByText('0')).toBeInTheDocument());
    });

    test('shows example text', async () => {
        render(<Tokenizer />);
        fireEvent.click(screen.getByText(/Show example/i));
        await waitFor(() => expect(screen.getByDisplayValue('300000')).toBeInTheDocument());
    });
});
