// Generated by Copilot

export type Todo = { id: number; text: string; completed: boolean };
export type User = { id: number; name: string; email: string };
export type Notification = { id: number; message: string; type: "info" | "warning" | "error" };

export type HistoryAction =
  | { type: "add"; value: string }
  | { type: "undo" }
  | { type: "redo" };

export type HistoryState = {
  past: string[];
  present: string;
  future: string[];
};
